
exec sp_ranking_condominio @dt_inicio= '2000-06-21', @dt_termino= '2023-06-30';

-- Exercicio 7
exec sp_diasuteis @dt_inicio= '2023-06-21', @dt_termino= '2023-06-30';

-- Exercicio 8-a)
SELECT A.CODIGO_EDIFICIO, A.NOME_EDIFICIO, A.ANDARES, A.APARTAMENTOS_POR_ANDAR, B.NOME_CIDADE, B.ESTADO
  FROM TABELA_EDIFICIO A
 INNER JOIN TABELA_CIDADE B ON B.CODIGO_CIDADE = A.CODIGO_CIDADE
 INNER JOIN TABELA_APARTAMENTO C ON C.CODIGO_EDIFICIO = A.CODIGO_EDIFICIO
  WHERE B.ESTADO = 'SP'
    AND (A.ANDARES * A.APARTAMENTOS_POR_ANDAR) = 30
    AND C.NUMERO_QUARTOS >= 2
    AND C.METRAGEM >= 100
GROUP BY A.CODIGO_EDIFICIO, A.NOME_EDIFICIO, A.ANDARES, A.APARTAMENTOS_POR_ANDAR, B.NOME_CIDADE, B.ESTADO  
  ORDER BY  MIN(C.METRAGEM) DESC;

-- Exercicio 8-b)
SELECT TOP 1 A.CODIGO_APARTAMENTO, SUM(VALOR_PAGAMENTO) AS VALOR
FROM TABELA_PAGAMENTOS_CONDOMINIO A
INNER JOIN TABELA_APARTAMENTO B ON B.CODIGO_APARTAMENTO = A.CODIGO_APARTAMENTO
INNER JOIN TABELA_EDIFICIO C ON C.CODIGO_EDIFICIO = B.CODIGO_EDIFICIO
INNER JOIN TABELA_CIDADE D ON D.CODIGO_CIDADE = C.CODIGO_CIDADE
WHERE YEAR(A.DATA_PAGAMENTO) = 2011
AND D.ESTADO = 'SP'
GROUP BY A.CODIGO_APARTAMENTO
ORDER BY VALOR DESC;