-- exec sp_ranking_condominio @dt_inicio= '2023-06-21', @dt_termino= '2023-06-21';

/*SELECT A.CODIGO_EDIFICIO, B.*
  FROM TABELA_EDIFICIO A
 INNER JOIN TABELA_CIDADE B ON B.CODIGO_CIDADE = A.CODIGO_CIDADE
 WHERE B.ESTADO = 'SP'
   AND (A.ANDARES * A.APARTAMENTOS_POR_ANDAR) = 30
   AND EXISTS ( SELECT CODIGO_APARTAMENTO
                  FROM TABELA_APARTAMENTO X
                 WHERE X.CODIGO_EDIFICIO = A.CODIGO_EDIFICIO
                   AND X.NUMERO_QUARTOS >= 2
                   AND X.METRAGEM >= 100);

*/


/*SELECT A.CODIGO_EDIFICIO, A.NOME_EDIFICIO, A.ANDARES, A.APARTAMENTOS_POR_ANDAR, B.NOME_CIDADE, B.ESTADO
  FROM TABELA_EDIFICIO A
 INNER JOIN TABELA_CIDADE B ON B.CODIGO_CIDADE = A.CODIGO_CIDADE
 INNER JOIN TABELA_APARTAMENTO C ON C.CODIGO_EDIFICIO = A.CODIGO_EDIFICIO
  WHERE B.ESTADO = 'SP'
    AND (A.ANDARES * A.APARTAMENTOS_POR_ANDAR) = 30
    AND C.NUMERO_QUARTOS >= 2
    AND C.METRAGEM >= 100
  ORDER BY  C.METRAGEM DESC*/
   